---
- name: Install programs on Fedora
  hosts: localhost
  vars:
    tmp_folder: /tmp/ansible_temp
  become: yes
  tasks:

  - name: Create temp download folder
    command: >
       mkdir -p {{ tmp_folder }}

  - name: Import GPG Keys
    rpm_key:
        state: present
        key: "{{ item }}"
    with_items:
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
        - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
        - https://packages.microsoft.com/keys/microsoft.asc
        - https://dl.google.com/linux/linux_signing_key.pub
       
  - name: Importing Repositories
    dnf:
       name: "{{ item }}"
       state: present
    with_items:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
        #- https://packages.microsoft.com/yumrepos/vscode
        #- http://dl.google.com/linux/chrome/rpm/stable/$basearch

  - name: Add repository into repo.d list
    ansible.builtin.yum_repository:
        name: google-chrome
        description: google-chrome repository
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled: true
        gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub

  - name: Add repository into repo.d list
    ansible.builtin.yum_repository:
        name: vscode
        description: vscode repository
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        
  - name: Add flathub repository
    command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Refreshing the repos cache
    shell: |
        yum update --refresh git-core
  
  - name: Install commom programs
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - flatpak
      - vim
      - snapd
      - code
      - curl
      - wget
      - flameshot
      - yakuake
      - onedrive
      #- https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - firefox
      - qbittorrent
      - gwe #Gree with Envy - Nvidia Tweaks
      - google-chrome-stable
  
  #- name: Install snap programs
  #  snap:
  #    name: "{{ item }}"
  #    state: present
  #  with_items:
  #      - deezer
      
  - name: Install flatpak programs
    flatpak:
      name: "{{ item }}"
      remote: flathub
      state: present
    with_items:
      - org.meetfranz.Franz
      - com.notepadqq.Notepadqq
      - io.github.peazip.PeaZip
      - io.dbeaver.DBeaverCommunity
      - dev.aunetx.deezer


  - name: Install AppImageLaucher
    shell: |
      cd "{{ tmp_folder }}"
      wget https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | xargs wget
      rm -f appimagelauncher*.tar.xz
      rm -f appoimagelauncher-lite*
      rm -f appimagelauncher*.arm*
      rm -f appimagelauncher*.deb
      rm -f appimagelauncher*.i386*
      rpm -Uvh *rpm 

  - name: Install AWS CLI
    shell: |
      cd {{ tmp_folder }}
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
       

  - name: Install AWS SSM Plugin
    dnf:
      name: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      state: present
       
  - name: Install OneDriveGui
    shell: |
       cd "{{ tmp_folder }}"
       wget https://api.github.com/repos/bpozdena/OneDriveGUI/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | xargs wget
       find . -type f -name "*.txt" -exec ail-cli integrate {} \; 

  - name: Install Serverless Framework
    shell: |
        curl -o- -L https://slss.io/install | bash

  - name: Install Python 3.9 - Requirements
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - wget 
      - yum-utils 
      - make 
      - gcc 
      - openssl-devel 
      - bzip2-devel 
      - libffi-devel 
      - zlib-devel 
  - name: Install Python 3.9 - Install
    shell: |
        cd "{{ tmp_folder }}"
        wget https://www.python.org/ftp/python/3.9.18/Python-3.9.18.tgz
        tar xzf Python-3.9.18.tgz
        cd Python-3.9.18
        sudo ./configure --with-system-ffi --with-computed-gotos --enable-loadable-sqlite-extensions
        sudo make -j
        sudo make altinstall
        cd "{{ tmp_folder }}"
   
  - name: Cleaing temp folder
    shell: |
        cd "{{ tmp_folder }}"
        rm -rf ./*.*
        
       
  

