---
- name: Install programs on Fedora
  hosts: localhost
  vars:
    tmp_folder: /tmp/ansible_temp
  become: yes
  tasks:

  - name: Check if SSM key already exists
    stat:
       path: "{{ tmp_folder }}/amazon-ssm-agent.gpg"
    register: file_status

  - name: Create temp download folder
    shell: |
       mkdir -p {{ tmp_folder }}
       cp ./amazon-ssm-agent.gpg {{ tmp_folder }}
    when: not file_status.stat.exists


  - name: Adding RPM Free repository into repo.d list
    yum_repository:
        name: RPM-Fusion-Free
        description: RPM Free repository
        baseurl: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        enabled: true
        gpgcheck: true
        gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

  - name: Adding RPM Non Free repository into repo.d list
    yum_repository:
        name: RPM-Fusion-NonFree
        description: RPM Non Free repository
        baseurl: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
        enabled: true
        gpgcheck: true
        gpgkey: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

  - name: Adding Google Chrome repository into repo.d list
    yum_repository:
        name: google-chrome
        description: google-chrome repository
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        enabled: true
        gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub

  - name: Adding Microsoft VSCode repository into repo.d list
    yum_repository:
        name: vscode
        description: vscode repository
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        
  - name: Adding Notion Repackged repository into repo.d list
    yum_repository:
        name: notion-repackged
        description: notion repackaged repository
        baseurl: https://yum.fury.io/notion-repackaged/
        enabled: true
        gpgcheck: false

  - name: Download AppImageLaucher
    shell: |
        wget https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url.*\.rpm/ && !/i386/ && !/armhf/ {print $(NF-1)}' | xargs wget
        find . -name "*.rpm" -exec mv {} ./appimagelauncher.rpm \;
    args:
        chdir: "{{ tmp_folder }}"

  - name: Install AppImageLauncher
    dnf:
        name: "{{ tmp_folder }}/appimagelauncher.rpm"
        state: present
        disable_gpg_check: true

  - name: Removinf AppImageLauncher package
    file:
        state: absent
        path: "{{ tmp_folder }}/appimagelauncher.rpm"
      
  - name: Add flathub repository
    command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Refreshing the repos cache
    shell: |
        yum update --refresh git-core
  
  - name: Install commom programs
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - flatpak
      - vim
      - code
      - curl
      - wget
      - flameshot
      - yakuake
      - onedrive
      - firefox
      - qbittorrent
      - gwe #Gree with Envy - Nvidia Tweaks
      - google-chrome-stable
      - notion-app-enhanced
      
  - name: Install flatpak programs
    flatpak:
      name: "{{ item }}"
      remote: flathub
      state: present
    with_items:
      - com.meetfranz.Franz
      - com.notepadqq.Notepadqq
      - io.github.peazip.PeaZip
      - io.dbeaver.DBeaverCommunity
      - dev.aunetx.deezer

  - name: Install AppImageLauncher
    dnf:

  - name: Download AWS CLI
    get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: "{{ tmp_folder }}/awscliv2.zip"
    tags:
      - download

  - name: Unzip AWS CLI
    unarchive:
        src: "{{ tmp_folder }}/awscliv2.zip"
        dest: "{{ tmp_folder }}"
        remote_src: yes

  - name: Installing AWS CLI
    shell: sudo ./aws/install
    register: ret
    args:
        chdir: "{{ tmp_folder }}"
    failed_when: ret.rc != 0 and ret.rc != 1
    

  - name: Delete AWS CLI Package
    file:
        state: absent
        path: "{{ tmp_folder }}/awscliv2.zip"
      
  - name: Importing AWS SSM Plugin GPG Key
    rpm_key:
        state: present
        key: "{{ tmp_folder }}/amazon-ssm-agent.gpg"
       

  - name: Install AWS SSM Plugin
    dnf:
      name: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
      state: present
      disable_gpg_check: true
       
  - name: Install OneDriveGui
    shell: |
       wget https://api.github.com/repos/bpozdena/OneDriveGUI/releases/latest -O - | awk -F \" -v RS="," '/browser_download_url/ {print $(NF-1)}' | xargs wget
       find . -type f -name "*.AppImage" -exec ail-cli integrate {} \; 
    args:
        chdir: "{{ tmp_folder }}"

  - name: Install Serverless Framework
    shell: |
        curl -o- -L https://slss.io/install | bash

  - name: Cleaing temp folder
    shell: |
        cd "{{ tmp_folder }}"
        rm -rf ./*.*
        
       
  

